/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardDeviceDTO"][];
                        "application/json": components["schemas"]["DashboardDeviceDTO"][];
                        "text/json": components["schemas"]["DashboardDeviceDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDeviceDto"];
                    "text/json": components["schemas"]["CreateDeviceDto"];
                    "application/*+json": components["schemas"]["CreateDeviceDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Device"];
                        "application/json": components["schemas"]["Device"];
                        "text/json": components["schemas"]["Device"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateDeviceDto"];
                    "text/json": components["schemas"]["UpdateDeviceDto"];
                    "application/*+json": components["schemas"]["UpdateDeviceDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    sensorId?: number;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown[][];
                        "application/json": unknown[][];
                        "text/json": unknown[][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SensorSettings"][];
                        "application/json": components["schemas"]["SensorSettings"][];
                        "text/json": components["schemas"]["SensorSettings"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSensorDto"];
                    "text/json": components["schemas"]["CreateSensorDto"];
                    "application/*+json": components["schemas"]["CreateSensorDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SensorSettings"];
                        "application/json": components["schemas"]["SensorSettings"];
                        "text/json": components["schemas"]["SensorSettings"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateSensorDto"];
                    "text/json": components["schemas"]["UpdateSensorDto"];
                    "application/*+json": components["schemas"]["UpdateSensorDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/device/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SensorSettings"][];
                        "application/json": components["schemas"]["SensorSettings"][];
                        "text/json": components["schemas"]["SensorSettings"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemConfig"];
                        "application/json": components["schemas"]["SystemConfig"];
                        "text/json": components["schemas"]["SystemConfig"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemConfig"];
                    "text/json": components["schemas"]["SystemConfig"];
                    "application/*+json": components["schemas"]["SystemConfig"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemStatus"][];
                        "application/json": components["schemas"]["SystemStatus"][];
                        "text/json": components["schemas"]["SystemStatus"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateDeviceDto: {
            name?: string | null;
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            /** Format: int32 */
            slaveId?: number;
            isActive?: boolean;
        };
        CreateSensorDto: {
            /** Format: int32 */
            deviceId?: number;
            /** Format: int32 */
            portNumber?: number;
            name?: string | null;
            slug?: string | null;
            dataType?: string | null;
            unit?: string | null;
            uiConfig?: string | null;
        };
        DashboardDeviceDTO: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            /** Format: int32 */
            slaveId?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            sensors?: components["schemas"]["DashboardSensorDTO"][] | null;
            /** Format: int32 */
            totalSensors?: number;
        };
        DashboardSensorDTO: {
            /** Format: int32 */
            sensorId?: number;
            /** Format: int32 */
            deviceId?: number;
            /** Format: int32 */
            portNumber?: number;
            name?: string | null;
            slug?: string | null;
            sensorDataType?: components["schemas"]["SensorDataType"];
            unit?: string | null;
            uiConfigJson?: components["schemas"]["SensorUiConfig"];
            /** Format: date-time */
            updatedAt?: string;
        };
        Device: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            sensors?: components["schemas"]["SensorSettings"][] | null;
            /** Format: int32 */
            totalSensors?: number;
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            /** Format: int32 */
            slaveId?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        SensorDataType: "ANALOG" | "DIGITAL" | "VIRTUAL";
        SensorSettings: {
            /** Format: int32 */
            sensorId?: number;
            /** Format: int32 */
            deviceId?: number | null;
            /** Format: int32 */
            portNumber?: number | null;
            name?: string | null;
            slug?: string | null;
            dataType?: components["schemas"]["SensorDataType"];
            unit?: string | null;
            /** Format: double */
            inputMin?: number;
            /** Format: double */
            inputMax?: number;
            /** Format: double */
            outputMin?: number;
            /** Format: double */
            outputMax?: number;
            /** Format: double */
            offsetVal?: number;
            formula?: string | null;
            uiConfigJson?: components["schemas"]["SensorUiConfig"];
            /** Format: date-time */
            updatedAt?: string;
        };
        SensorUiConfig: {
            color?: string | null;
            /** Format: double */
            minCritical?: number | null;
            /** Format: double */
            minWarning?: number | null;
            /** Format: double */
            maxWarning?: number | null;
            /** Format: double */
            maxCritical?: number | null;
            /** Format: double */
            digitalWarning?: number | null;
            /** Format: double */
            digitalCritical?: number | null;
            labelZero?: string | null;
            labelOne?: string | null;
        };
        /** @enum {string} */
        ServiceStatus: "ONLINE" | "OFFLINE" | "DEGRADED" | "CRITICAL_ERROR" | "MAINTENANCE";
        SystemConfig: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            rawRetentionDays?: number;
            /** Format: int32 */
            aggRetentionDays?: number;
            /** Format: int32 */
            pollingIntervalMs?: number;
            /** Format: int32 */
            configReloadIntervalSec?: number;
            /** Format: int32 */
            healthCheckIntervalSec?: number;
            /** Format: double */
            deadbandThreshold?: number;
            /** Format: int32 */
            dataHeartbeatSec?: number;
            /** Format: int32 */
            uiUpdateIntervalMs?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        SystemStatus: {
            serviceName?: string | null;
            status?: components["schemas"]["ServiceStatus"];
            /** Format: int64 */
            uptimeSeconds?: number;
            lastError?: string | null;
            /** Format: date-time */
            lastSync?: string;
        };
        UpdateDeviceDto: {
            name?: string | null;
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            /** Format: int32 */
            slaveId?: number;
            isActive?: boolean;
        };
        UpdateSensorDto: {
            /** Format: int32 */
            portNumber?: number;
            name?: string | null;
            slug?: string | null;
            dataType?: string | null;
            unit?: string | null;
            uiConfig?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
