/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModbusConnection"][];
                        "application/json": components["schemas"]["ModbusConnection"][];
                        "text/json": components["schemas"]["ModbusConnection"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateConnectionDto"];
                    "text/json": components["schemas"]["CreateConnectionDto"];
                    "application/*+json": components["schemas"]["CreateConnectionDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ModbusConnection"];
                        "application/json": components["schemas"]["ModbusConnection"];
                        "text/json": components["schemas"]["ModbusConnection"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateConnectionDto"];
                    "text/json": components["schemas"]["UpdateConnectionDto"];
                    "application/*+json": components["schemas"]["UpdateConnectionDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WriteCommandDto"];
                    "text/json": components["schemas"]["WriteCommandDto"];
                    "application/*+json": components["schemas"]["WriteCommandDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardDeviceDTO"][];
                        "application/json": components["schemas"]["DashboardDeviceDTO"][];
                        "text/json": components["schemas"]["DashboardDeviceDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDeviceDto"];
                    "text/json": components["schemas"]["CreateDeviceDto"];
                    "application/*+json": components["schemas"]["CreateDeviceDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Device"];
                        "application/json": components["schemas"]["Device"];
                        "text/json": components["schemas"]["Device"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateDeviceDto"];
                    "text/json": components["schemas"]["UpdateDeviceDto"];
                    "application/*+json": components["schemas"]["UpdateDeviceDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    tagId?: number;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown[][];
                        "application/json": unknown[][];
                        "text/json": unknown[][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemConfig"];
                        "application/json": components["schemas"]["SystemConfig"];
                        "text/json": components["schemas"]["SystemConfig"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemConfig"];
                    "text/json": components["schemas"]["SystemConfig"];
                    "application/*+json": components["schemas"]["SystemConfig"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemStatus"][];
                        "application/json": components["schemas"]["SystemStatus"][];
                        "text/json": components["schemas"]["SystemStatus"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagSettings"][];
                        "application/json": components["schemas"]["TagSettings"][];
                        "text/json": components["schemas"]["TagSettings"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTagDto"];
                    "text/json": components["schemas"]["CreateTagDto"];
                    "application/*+json": components["schemas"]["CreateTagDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagSettings"];
                        "application/json": components["schemas"]["TagSettings"];
                        "text/json": components["schemas"]["TagSettings"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTagDto"];
                    "text/json": components["schemas"]["UpdateTagDto"];
                    "application/*+json": components["schemas"]["UpdateTagDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/device/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagSettings"][];
                        "application/json": components["schemas"]["TagSettings"][];
                        "text/json": components["schemas"]["TagSettings"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateConnectionDto: {
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            description?: string | null;
        };
        CreateDeviceDto: {
            name?: string | null;
            /** Format: int32 */
            connectionId?: number;
            /** Format: int32 */
            slaveId?: number;
            useGroupPolling?: boolean;
            /** Format: int32 */
            maxRegisterSpan?: number;
            isActive?: boolean;
            /** Format: int32 */
            maxBitSpan?: number;
        };
        CreateTagDto: {
            /** Format: int32 */
            deviceId?: number;
            /** Format: int32 */
            portNumber?: number;
            name?: string | null;
            slug?: string | null;
            dataType?: string | null;
            /** Format: int32 */
            registerAddress?: number;
            registerType?: string | null;
            /** Format: int32 */
            registerCount?: number;
            unit?: string | null;
            /** Format: double */
            inputMin?: number;
            /** Format: double */
            inputMax?: number;
            /** Format: double */
            outputMin?: number;
            /** Format: double */
            outputMax?: number;
            /** Format: double */
            offsetVal?: number;
            formula?: string | null;
            uiConfig?: string | null;
            endianness?: string | null;
            /** Format: double */
            deadbandThreshold?: number | null;
            rawDataType?: string | null;
        };
        DashboardDeviceDTO: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            /** Format: int32 */
            connectionId?: number;
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            /** Format: int32 */
            slaveId?: number;
            useGroupPolling?: boolean;
            /** Format: int32 */
            maxRegisterSpan?: number;
            isActive?: boolean;
            isOnline?: boolean;
            /** Format: date-time */
            lastSeen?: string | null;
            /** Format: date-time */
            createdAt?: string;
            tags?: components["schemas"]["DashboardTagDTO"][] | null;
            /** Format: int32 */
            totalTags?: number;
        };
        DashboardTagDTO: {
            /** Format: int32 */
            tagId?: number;
            /** Format: int32 */
            deviceId?: number;
            /** Format: int32 */
            portNumber?: number;
            name?: string | null;
            slug?: string | null;
            dataType?: components["schemas"]["TagDataType"];
            unit?: string | null;
            uiConfigJson?: components["schemas"]["TagUiConfig"];
            /** Format: date-time */
            updatedAt?: string;
        };
        Device: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            tags?: components["schemas"]["TagSettings"][] | null;
            /** Format: int32 */
            totalTags?: number;
            /** Format: int32 */
            connectionId?: number;
            /** Format: int32 */
            slaveId?: number;
            useGroupPolling?: boolean;
            /** Format: int32 */
            maxRegisterSpan?: number;
            /** Format: int32 */
            maxBitSpan?: number;
            isActive?: boolean;
            isOnline?: boolean;
            /** Format: date-time */
            lastSeen?: string | null;
            lastConnError?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ModbusConnection: {
            /** Format: int32 */
            id?: number;
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            description?: string | null;
        };
        /** @enum {string} */
        ModbusEndianness: "BIG_ENDIAN" | "LITTLE_ENDIAN" | "WORD_SWAP" | "BYTE_WORD_SWAP";
        /** @enum {string} */
        ModbusRegisterType: "INPUT_REGISTER" | "HOLDING_REGISTER" | "DISCRETE_INPUT" | "COIL";
        /** @enum {string} */
        RawDataType: "INT16" | "U_INT16" | "INT32" | "U_INT32" | "FLOAT32" | "FLOAT64";
        /** @enum {string} */
        ServiceStatus: "ONLINE" | "OFFLINE" | "DEGRADED" | "CRITICAL_ERROR" | "MAINTENANCE";
        SystemConfig: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            rawRetentionDays?: number;
            /** Format: int32 */
            aggRetentionDays?: number;
            /** Format: int32 */
            pollingIntervalMs?: number;
            /** Format: int32 */
            configReloadIntervalSec?: number;
            /** Format: int32 */
            healthCheckIntervalSec?: number;
            /** Format: double */
            deadbandThreshold?: number;
            /** Format: int32 */
            dataHeartbeatSec?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        SystemStatus: {
            serviceName?: string | null;
            status?: components["schemas"]["ServiceStatus"];
            /** Format: int64 */
            uptimeSeconds?: number;
            lastError?: string | null;
            /** Format: date-time */
            lastSync?: string;
        };
        /** @enum {string} */
        TagDataType: "ANALOG_RAW" | "ANALOG_PHYSICAL" | "DIGITAL" | "VIRTUAL";
        TagSettings: {
            /** Format: int32 */
            tagId?: number;
            /** Format: int32 */
            deviceId?: number | null;
            /** Format: int32 */
            portNumber?: number | null;
            /** Format: int32 */
            registerAddress?: number;
            registerType?: components["schemas"]["ModbusRegisterType"];
            /** Format: int32 */
            registerCount?: number;
            rawDataType?: components["schemas"]["RawDataType"];
            endianness?: components["schemas"]["ModbusEndianness"];
            name?: string | null;
            slug?: string | null;
            dataType?: components["schemas"]["TagDataType"];
            unit?: string | null;
            /** Format: double */
            inputMin?: number;
            /** Format: double */
            inputMax?: number;
            /** Format: double */
            outputMin?: number;
            /** Format: double */
            outputMax?: number;
            /** Format: double */
            offsetVal?: number;
            /** Format: double */
            deadbandThreshold?: number | null;
            formula?: string | null;
            uiConfigJson?: components["schemas"]["TagUiConfig"];
            /** Format: date-time */
            updatedAt?: string;
        };
        TagUiConfig: {
            color?: string | null;
            /** Format: double */
            minCritical?: number | null;
            /** Format: double */
            minWarning?: number | null;
            /** Format: double */
            maxWarning?: number | null;
            /** Format: double */
            maxCritical?: number | null;
            /** Format: double */
            digitalWarning?: number | null;
            /** Format: double */
            digitalCritical?: number | null;
            labelZero?: string | null;
            labelOne?: string | null;
        };
        UpdateConnectionDto: {
            ipAddress?: string | null;
            /** Format: int32 */
            port?: number;
            description?: string | null;
        };
        UpdateDeviceDto: {
            name?: string | null;
            /** Format: int32 */
            connectionId?: number;
            /** Format: int32 */
            slaveId?: number;
            useGroupPolling?: boolean;
            /** Format: int32 */
            maxRegisterSpan?: number;
            isActive?: boolean;
            /** Format: int32 */
            maxBitSpan?: number;
        };
        UpdateTagDto: {
            /** Format: int32 */
            portNumber?: number;
            name?: string | null;
            slug?: string | null;
            dataType?: string | null;
            /** Format: int32 */
            registerAddress?: number;
            registerType?: string | null;
            /** Format: int32 */
            registerCount?: number;
            unit?: string | null;
            /** Format: double */
            inputMin?: number;
            /** Format: double */
            inputMax?: number;
            /** Format: double */
            outputMin?: number;
            /** Format: double */
            outputMax?: number;
            /** Format: double */
            offsetVal?: number;
            formula?: string | null;
            uiConfig?: string | null;
            endianness?: string | null;
            /** Format: double */
            deadbandThreshold?: number | null;
            rawDataType?: string | null;
        };
        WriteCommandDto: {
            /** Format: int32 */
            tagId?: number;
            /** Format: double */
            value?: number;
            operatorId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
