export const icons = {
  // Navigation & General
  arrowDown: "i-ph-arrow-down",
  arrowLeft: "i-ph-arrow-left",
  arrowRight: "i-ph-arrow-right",
  arrowUp: "i-ph-arrow-up",
  chevronDown: "i-ph-caret-down",
  chevronLeft: "i-ph-caret-left",
  chevronRight: "i-ph-caret-right",
  chevronUp: "i-ph-caret-up",
  home: "i-ph-house",
  menu: "i-ph-list",
  search: "i-ph-magnifying-glass",
  reload: "i-ph-arrow-counter-clockwise",
  close: "i-ph-x",
  plus: "i-ph-plus",
  minus: "i-ph-minus",
  ellipsis: "i-ph-dots-three",
  drag: "i-ph-dots-six-vertical",

  // Admin & Identity
  user: "i-ph-user",
  users: "i-ph-users",
  userCircle: "i-ph-user-circle",
  shield: "i-ph-shield-check",
  lock: "i-ph-lock",
  key: "i-ph-key",

  // IoT & Devices
  device: "i-ph-cpu",
  devices: "i-ph-devices",
  sensor: "i-ph-broadcast",
  gateway: "ph:flow-arrow",
  plug: "i-ph-plug",
  battery: "i-ph-battery-charging",
  signal: "i-ph-broadcast",
  door: "i-ph-door",

  // Monitoring & Analytics
  dashboard: "i-ph-layout",
  chart: "i-ph-chart-line-up",
  barChart: "i-ph-chart-bar",
  pieChart: "i-ph-chart-pie",
  activity: "i-ph-activity",
  gauge: "i-ph-gauge",
  timer: "i-ph-timer",

  // Status & Alerts
  info: "i-ph-info",
  warning: "i-ph-warning",
  error: "i-ph-x-circle",
  success: "i-ph-check-circle",
  caution: "i-ph-warning-circle",
  check: "i-ph-check",
  notification: "i-ph-bell",
  notificationActive: "i-ph-bell-ringing",

  // Actions & Operations
  settings: "i-ph-gear",
  edit: "i-ph-pencil-line",
  delete: "i-ph-trash",
  copy: "i-ph-copy",
  copyCheck: "i-ph-check-circle",
  save: "i-ph-floppy-disk",
  upload: "i-ph-upload",
  download: "i-ph-download",
  export: "i-ph-export",
  share: "i-ph-share-network",
  eye: "i-ph-eye",
  eyeOff: "i-ph-eye-slash",

  // Misc
  file: "i-ph-file",
  folder: "i-ph-folder",
  folderOpen: "i-ph-folder-open",
  hash: "i-ph-hash",
  calendar: "i-ph-calendar",
  dark: "i-ph-moon",
  light: "i-ph-sun",
  system: "i-ph-monitor",
  terminal: "i-ph-terminal-window",
  database: "i-ph-database",
  cloud: "i-ph-cloud",
} as const;
