const icons = {
  // App logo
  appLogoIcon: "ph:bounding-box-duotone",

  // Navigation & General
  arrowDownIcon: "ph:arrow-down",
  arrowLeftIcon: "ph:arrow-left",
  arrowRightIcon: "ph:arrow-right",
  arrowUpIcon: "ph:arrow-up",
  chevronDownIcon: "ph:caret-down",
  chevronLeftIcon: "ph:caret-left",
  chevronRightIcon: "ph:caret-right",
  chevronUpIcon: "ph:caret-up",
  chevronUpDownIcon: "ph:caret-up-down",
  widerIcon: "ph:arrow-line-right",
  narrowerIcon: "ph:arrow-line-left",
  homeIcon: "ph:house",
  menuIcon: "ph:list",
  viewCardsIcon: "ph:squares-four",
  viewTableIcon: "ph:table",
  expandIcon: "ph:arrows-out",
  searchIcon: "ph:magnifying-glass",
  reloadIcon: "ph:arrow-counter-clockwise",
  closeIcon: "ph:x",
  plusIcon: "ph:plus",
  minusIcon: "ph:minus",
  ellipsisIcon: "ph:dots-three",
  dragIcon: "ph:dots-six-vertical",
  filtersIcon: "ph:faders-horizontal",

  // Admin & Identity
  userIcon: "ph:user",
  usersIcon: "ph:users",
  userCircleIcon: "ph:user-circle",
  shieldIcon: "ph:shield-check",
  lockIcon: "ph:lock",
  keyIcon: "ph:key",

  // IoT & Devices
  deviceIcon: "ph:cpu",
  devicesIcon: "ph:devices",
  tagIcon: "ph:tag",
  connectionIcon: "ph:plug",
  gatewayIcon: "ph:flow-arrow",
  controlIcon: "ph:sliders-horizontal",
  plugIcon: "ph:plug",
  batteryIcon: "ph:battery-charging",
  signalIcon: "ph:broadcast",
  doorIcon: "ph:door",
  binaryIcon: "ph:binary",

  // Monitoring & Analytics
  dashboardIcon: "ph:layout",
  chartIcon: "ph:chart-line-up",
  barChartIcon: "ph:chart-bar",
  pieChartIcon: "ph:chart-pie",
  activityIcon: "ph:activity",
  gaugeIcon: "ph:gauge",
  timerIcon: "ph:timer",
  branchIcon: "ph:git-branch",

  // Status & Alerts
  infoIcon: "ph:info",
  warningIcon: "ph:warning",
  errorIcon: "ph:x-circle",
  successIcon: "ph:check-circle",
  cautionIcon: "ph:warning-circle",
  checkIcon: "ph:check",
  notificationIcon: "ph:bell",
  notificationActiveIcon: "ph:bell-ringing",

  // Actions & Operations
  settingsIcon: "ph:gear",
  editIcon: "ph:pencil-line",
  deleteIcon: "ph:trash",
  copyIcon: "ph:copy",
  copyCheckIcon: "ph:check-circle",
  saveIcon: "ph:floppy-disk",
  uploadIcon: "ph:upload",
  downloadIcon: "ph:download",
  exportIcon: "ph:export",
  shareIcon: "ph:share-network",
  eyeIcon: "ph:eye",
  eyeOffIcon: "ph:eye-slash",

  // Misc
  fileIcon: "ph:file",
  folderIcon: "ph:folder",
  folderOpenIcon: "ph:folder-open",
  hashIcon: "ph:hash",
  calendarIcon: "ph:calendar",
  darkIcon: "ph:moon",
  lightIcon: "ph:sun",
  systemIcon: "ph:monitor",
  terminalIcon: "ph:terminal-window",
  databaseIcon: "ph:database",
  cloudIcon: "ph:cloud",
  githubIcon: "ph:github-logo",
} as const;

export default icons;

export const {
  appLogoIcon,
  arrowDownIcon,
  arrowLeftIcon,
  arrowRightIcon,
  filtersIcon,
  arrowUpIcon,
  chevronDownIcon,
  chevronLeftIcon,
  chevronRightIcon,
  chevronUpIcon,
  chevronUpDownIcon,
  widerIcon,
  narrowerIcon,
  homeIcon,
  menuIcon,
  viewCardsIcon,
  viewTableIcon,
  expandIcon,
  searchIcon,
  reloadIcon,
  closeIcon,
  plusIcon,
  minusIcon,
  ellipsisIcon,
  dragIcon,
  userIcon,
  usersIcon,
  userCircleIcon,
  shieldIcon,
  lockIcon,
  keyIcon,
  deviceIcon,
  devicesIcon,
  tagIcon,
  connectionIcon,
  gatewayIcon,
  controlIcon,
  plugIcon,
  batteryIcon,
  signalIcon,
  doorIcon,
  binaryIcon,
  dashboardIcon,
  chartIcon,
  barChartIcon,
  pieChartIcon,
  activityIcon,
  gaugeIcon,
  timerIcon,
  branchIcon,
  infoIcon,
  warningIcon,
  errorIcon,
  successIcon,
  cautionIcon,
  checkIcon,
  notificationIcon,
  notificationActiveIcon,
  settingsIcon,
  editIcon,
  deleteIcon,
  copyIcon,
  copyCheckIcon,
  saveIcon,
  uploadIcon,
  downloadIcon,
  exportIcon,
  shareIcon,
  eyeIcon,
  eyeOffIcon,
  fileIcon,
  folderIcon,
  folderOpenIcon,
  hashIcon,
  calendarIcon,
  darkIcon,
  lightIcon,
  systemIcon,
  terminalIcon,
  databaseIcon,
  cloudIcon,
  githubIcon,
} = icons;

/** Nuxt UI ожидает ключи без суффикса Icon (chevronDown, check, close…) */
export const nuxtUiIcons = Object.fromEntries(
  Object.entries(icons).map(([k, v]) => [k.replace(/Icon$/, ""), v]),
) as Record<string, string>;
